# vim:fileencoding=utf-8:foldmethod=marker:foldmarker=<<<,>>>

# : Manager <<<

[mgr]
cwd = { fg = "#268bd2" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#d33682", bold = true, italic = true, underline = true }
find_position = { fg = "#2aa198", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#859900", bg = "#859900" }
marker_cut      = { fg = "#b58900", bg = "#dc322f" }
marker_marked   = { fg = "#268bd2", bg = "#2aa198" }
marker_selected = { fg = "#b58900", bg = "#b58900" }

# Count
count_copied   = { fg = "#073642", bg = "#859900" }
count_cut      = { fg = "#073642", bg = "#b58900" }
count_selected = { fg = "#073642", bg = "#268bd2" }

# Border
border_symbol = "│"
border_style  = { fg = "#586e75" }

# : >>>


# : Tabs <<<

[tabs]
active   = { fg = "#002b36", bg = "#268bd2", bold = true }
inactive = { fg = "#268bd2", bg = "#002b36" }

# : >>>


# : Mode <<<

[mode]

normal_main = { fg = "#002b36", bg = "#268bd2", bold = true }
normal_alt  = { fg = "#268bd2", bg = "#002b36" }

# Select mode
select_main = { fg = "#002b36", bg = "#859900", bold = true }
select_alt  = { fg = "#268bd2", bg = "#002b36" }

# Unset mode
unset_main = { fg = "#002b36", bg = "#d33682", bold = true }
unset_alt  = { fg = "#268bd2", bg = "#002b36" }

# : >>>


# : Status bar <<<

[status]
overall = { fg = "#268bd2" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }


# Progress
progress_label = { fg = "#002b36", bold = true }
progress_normal = { fg = "#268bd2", bg = "#002b36" }
progress_error = { fg = "#dc322f", bg = "#002b36" }

# Permissions
perm_sep   = { fg = "#586e75" }
perm_type  = { fg = "#268bd2" }
perm_read  = { fg = "#b58900" }
perm_write = { fg = "#dc322f" }
perm_exec  = { fg = "#859900" }


# : >>>

# : Pick <<<

[pick]
border = { fg = "#268bd2" }
active = { fg = "#d33682", bold = true }
inactive = {}

# : >>>


# : Input <<<

[input]
border   = { fg = "#268bd2" }
title    = {}
value    = {}
selected = { reversed = true }

# : >>>


# : Completion <<<

[cmp]
border = { fg = "#268bd2" }

# : >>>


# : Tasks <<<

[tasks]
border  = { fg = "#268bd2" }
title   = {}
hovered = { fg = "#d33682", underline = true }

# : >>>


# : Which <<<

[which]
mask            = { bg = "#073642" }
cand            = { fg = "#2aa198" }
rest            = { fg = "#586e75" }
desc            = { fg = "#d33682" }
separator       = "  "
separator_style = { fg = "#586e75" }

# : >>>


# : Help <<<

[help]
on      = { fg = "#859900" }
run     = { fg = "#d33682" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#002b36", bg = "#839496" }

# : >>>


# : Notify <<<

[notify]
title_info  = { fg = "#859900" }
title_warn  = { fg = "#dc322f" }
title_error = { fg = "#b58900" }

# : >>>


# : File-specific styles <<<

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b58900" },

    # Media
    { mime = "video/*", fg = "#d33682" },
    { mime = "audio/*", fg = "#d33682" },

    # Archives
    { mime = "application/zip",             fg = "#d33682" },
    { mime = "application/x-tar",           fg = "#d33682" },
    { mime = "application/x-bzip*",         fg = "#d33682" },
    { mime = "application/x-bzip2",         fg = "#d33682" },
    { mime = "application/x-7z-compressed", fg = "#d33682" },
    { mime = "application/x-rar",           fg = "#d33682" },
    { mime = "application/x-xz",            fg = "#d33682" },

    # Documents
    { mime = "application/doc",        fg = "#859900" },
    { mime = "application/epub+zip",   fg = "#859900" },
    { mime = "application/pdf",        fg = "#859900" },
    { mime = "application/rtf",        fg = "#859900" },
    { mime = "application/vnd.*",      fg = "#859900" },

    # Fallback
    { name = "*", fg = "#839496" },
    { name = "*/", fg = "#268bd2" }
]

# : >>>
