"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$hostname\
$shdo\
$custom\
$direnv\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$conda\
$python\
$c\
$lua\
$rust\
$line_break\
$character"""

right_format = """
$cmd_duration\
$time\
"""

[os]
disabled = false
format = """
[](fg:blue)\
[$symbol]($style)\
[](fg:blue)\
"""
style = "bold fg:black bg:blue"

[os.symbols]
Macos = "  "
Ubuntu = "  "
Windows = " 󰍲 " 

[hostname]
ssh_only = true
ssh_symbol = " "
format = """
[](fg:magenta)\
[$ssh_symbol$hostname]($style)\
[](fg:magenta)\
"""
style = "bold fg:black bg:magenta"

[sudo]
disabled = false
symbol = ' 󰿆 sudo'
format = """
[](fg:red)\
[$symbol]($style)\
[](fg:red)\
"""
style = "bold fg:black bg:red"

[custom.venv]
command = "basename \"$VIRTUAL_ENV\""
when = "test -n \"$VIRTUAL_ENV\""
format = """
[](fg:magenta)\
[$output]($style)\
[](fg:magenta)\
"""
style = "bold fg:black bg:magenta"

[direnv]
disabled = false
format = """
[](fg:cyan)\
[$symbol$allowed]($style)\
[](fg:cyan)\
"""
style = "bold fg:black bg:cyan"

[directory]
truncation_length = 5
truncation_symbol = ' '
truncate_to_repo = false
home_symbol = '󰋞 ~'
read_only = ' 󰌾 '
format = """
[](fg:cyan)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:cyan)\
"""
style = 'bold fg:black bg:cyan'
read_only_style = 'bold fg:black bg:cyan'

[git_branch]
symbol = '  '
truncation_length = 4
truncation_symbol = ''
style = 'bold fg:cyan bg:brblack'
format = """
[](fg:brblack)\
[$symbol$branch(:$remote_branch)]($style)\
"""

[git_status]
disabled = false
style = 'bold fg:red bg:brblack'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '\$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = """
[  ](fg:blue bg:brblack)\
[$all_status$ahead_behind]($style)\
"""

[git_metrics]
disabled = false
added_style = 'bold fg:green bg:brblack'
deleted_style = 'bold fg:blue bg:brblack'
format = """
[  ](fg:blue bg:brblack)\
[+$added]($added_style)[-$deleted]($deleted_style)[](fg:brblack)\
"""

[fill]
symbol = '─'
style = 'fg:brblack bg:none'

[python]
symbol = '[ ](fg:yellow bg:black)'
format = '[](fg:black)[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)[](fg:black)'
style = 'bold fg:yellow bg:black'

[c]
symbol = '[ ](fg:cyan bg:black)'
format = '[](fg:black)[ $symbol($version) ]($style)[](fg:black)'
style = 'bold fg:cyan bg:black'

[lua]
symbol = "[ ](fg:blue bg:black)"
format = '[](fg:black)[ ${symbol}(${version})]($style)[](fg:black)'
style = 'bold fg:blue bg:black'

[rust]
symbol = "[󱘗 ](fg:red bg:black)"
format = '[](fg:black)[ ${symbol}(${version})]($style)[](fg:black)'
style = 'bold fg:red bg:black'

[cmd_duration]
show_milliseconds = true
min_time = 500
format = '[󰞌 $duration ](fg:yellow)'

[time]
disabled = false
format = '[ $time](bold fg:white)'
time_format = '%T'

[character]
success_symbol = "[❯](bold blue)[❯](bold magenta)[❯](bold cyan)"
error_symbol = "[❯](bold red)[❯](bold magenta)[❯](bold yellow)"
