# Alacritty config (~/.config/alacritty/alacritty.toml)

[general]
import = ["blur.toml"]

[window]
decorations = "buttonless"
# Window padding (pixels)
padding = { x = 10, y = 10 }

# Background opacity (0.0-1.0)
# ~0.95 recommended
opacity = 0.75

# Left Option acts as Alt; Right Option is used as Meta
option_as_alt = "OnlyLeft"

[font]
# Set font family (Nerd Font recommended) and size
# e.g. "HackGen Console NF", "PlemolJP Console NF"
size = 13.0

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[env]
# Tell apps this is a 256-color terminal (ok if duplicated)
TERM = "xterm-256color"

# Solarized Dark color theme
[colors]
primary = { background = "#002b36", foreground = "#839496" }

[colors.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"


[colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[[keyboard.bindings]]
key = "B"
mods = "Command"
command = { program = "/bin/sh", args = ["-c", "${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/toggle_blur.sh"] }
