"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
palette = "solarized_dark"

# Solarized Dark Minimal Linked Bar (Expanded Support + Brew Tools)
format = """
[](base02)\
$os\
$directory\
$git_branch\
$git_status\
$sudo\
$direnv\
$custom\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$typst\
$terraform\
$vlang\
$vagrant\
$zig\
$azure\
$env_var\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$crystal\
$docker_context\
$kubernetes\
$jobs\
$status\
$cmd_duration\
[](base02)\
$line_break\
$character"""

[palettes.solarized_dark]
base03  = "#002b36"
base02  = "#073642"
base01  = "#586e75"
base00  = "#657b83"
base0   = "#839496"
base1   = "#93a1a1"
base2   = "#eee8d5"
base3   = "#fdf6e3"
yellow  = "#b58900"
orange  = "#cb4b16"
red     = "#dc322f"
magenta = "#d33682"
violet  = "#6c71c4"
blue    = "#268bd2"
cyan    = "#2aa198"
green   = "#859900"

# --- Core ---

[os]
disabled = false
style = "bg:base02 fg:base1"
format = "[$symbol]($style)"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰌽 "
Macos = "󰀵 "
Linux = "󰌽 "

[directory]
style = "bg:base02 fg:blue"
format = "[ $path ]($style)[$read_only]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[git_branch]
symbol = ""
style = "bg:base02 fg:violet"
format = "[[ $symbol $branch ](bg:base02 fg:violet)]($style)"

[git_status]
disabled = false
style = "bg:base02 fg:orange"
format = "[$all_status$ahead_behind]($style)"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[sudo]
disabled = false
style = "bg:base02 fg:red"
symbol = " "
format = "[ | $symbol]($style)"

[direnv]
disabled = false
style = "bg:base02 fg:orange"
symbol = "▼ "
format = "[ | $symbol$allowed]($style)"

# --- Custom (Venv for Nushell) ---
[custom.venv]
shell = ["nu", "-c"]
command = "($env.VIRTUAL_ENV | path basename)"
when = "($env.VIRTUAL_ENV | is-not-empty)"
style = "bg:base02 fg:cyan"
format = "[ |  $output]($style)"

# --- Runtimes & Tools ---

[package]
symbol = "󰏗 "
style = "bg:base02 fg:base1"
format = "[ | $symbol$version]($style)"

[aws]
symbol = " "
style = "bg:base02 fg:orange"
format = "[ | $symbol$profile]($style)"

[buf]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[c]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[cmake]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[cobol]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[conda]
symbol = " "
style = "bg:base02 fg:green"
format = "[ | $symbol$environment]($style)"

[crystal]
symbol = " "
style = "bg:base02 fg:base1"
format = "[ | $symbol$version]($style)"

[daml]
symbol = " "
style = "bg:base02 fg:yellow"
format = "[ | $symbol$version]($style)"

[dart]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[deno]
symbol = " "
style = "bg:base02 fg:green"
format = "[ | $symbol$version]($style)"

[dotnet]
symbol = "󰪮 "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[elixir]
symbol = " "
style = "bg:base02 fg:magenta"
format = "[ | $symbol$version]($style)"

[elm]
symbol = " "
style = "bg:base02 fg:cyan"
format = "[ | $symbol$version]($style)"

[erlang]
symbol = " "
style = "bg:base02 fg:red"
format = "[ | $symbol$version]($style)"

[fennel]
symbol = " "
style = "bg:base02 fg:green"
format = "[ | $symbol$version]($style)"

[gcloud]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$account]($style)"

[golang]
symbol = " "
style = "bg:base02 fg:cyan"
format = "[ | $symbol$version]($style)"

[gradle]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[guix_shell]
symbol = " "
style = "bg:base02 fg:yellow"
format = "[ | $symbol]($style)"

[haskell]
symbol = " "
style = "bg:base02 fg:magenta"
format = "[ | $symbol$version]($style)"

[haxe]
symbol = " "
style = "bg:base02 fg:orange"
format = "[ | $symbol$version]($style)"

[helm]
symbol = " "
style = "bg:base02 fg:base1"
format = "[ | $symbol$version]($style)"

[java]
symbol = " "
style = "bg:base02 fg:red"
format = "[ | $symbol$version]($style)"

[julia]
symbol = " "
style = "bg:base02 fg:magenta"
format = "[ | $symbol$version]($style)"

[kotlin]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[lua]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[memory_usage]
symbol = "󰍛 "
style = "bg:base02 fg:base1"
format = "[ | $symbol$ram]($style)"

[nim]
symbol = "󰆥 "
style = "bg:base02 fg:yellow"
format = "[ | $symbol$version]($style)"

[nix_shell]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol]($style)"

[nodejs]
symbol = " "
style = "bg:base02 fg:green"
format = "[ | $symbol$version]($style)"

[ocaml]
symbol = " "
style = "bg:base02 fg:yellow"
format = "[ | $symbol$version]($style)"

[opa]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[openstack]
symbol = " "
style = "bg:base02 fg:red"
format = "[ | $symbol$cloud]($style)"

[perl]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[php]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[pulumi]
symbol = " "
style = "bg:base02 fg:magenta"
format = "[ | $symbol$stack]($style)"

[purescript]
symbol = " "
style = "bg:base02 fg:base1"
format = "[ | $symbol$version]($style)"

[python]
symbol = " "
style = "bg:base02 fg:cyan"
format = "[ | $symbol$version]($style)"

[raku]
symbol = " "
style = "bg:base02 fg:magenta"
format = "[ | $symbol$version]($style)"

[red]
symbol = "󰝽 "
style = "bg:base02 fg:red"
format = "[ | $symbol$version]($style)"

[rlang]
symbol = "󰟔 "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[ruby]
symbol = " "
style = "bg:base02 fg:red"
format = "[ | $symbol$version]($style)"

[rust]
symbol = " "
style = "bg:base02 fg:orange"
format = "[ | $symbol$version]($style)"

[scala]
symbol = " "
style = "bg:base02 fg:red"
format = "[ | $symbol$version]($style)"

[solidity]
symbol = " "
style = "bg:base02 fg:base1"
format = "[ | $symbol$version]($style)"

[spack]
symbol = "◇ "
style = "bg:base02 fg:blue"
format = "[ | $symbol$environment]($style)"

[swift]
symbol = " "
style = "bg:base02 fg:orange"
format = "[ | $symbol$version]($style)"

[terraform]
symbol = "󱁢 "
style = "bg:base02 fg:violet"
format = "[ | $symbol$workspace]($style)"

[typst]
symbol = "t "
style = "bg:base02 fg:base1"
format = "[ | $symbol$version]($style)"

[vagrant]
symbol = " "
style = "bg:base02 fg:cyan"
format = "[ | $symbol$version]($style)"

[vlang]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$version]($style)"

[zig]
symbol = " "
style = "bg:base02 fg:yellow"
format = "[ | $symbol$version]($style)"

# --- Cloud/Containers ---

[docker_context]
symbol = " "
style = "bg:base02 fg:blue"
format = "[ | $symbol$context]($style)"

[kubernetes]
symbol = "󱃾 "
style = "bg:base02 fg:blue"
format = "[ | $symbol$context]($style)"

# --- System ---

[jobs]
symbol = " "
style = "bg:base02 fg:base1"
format = "[ | $symbol$number]($style)"

[status]
disabled = false
style = "bg:base02 fg:red"
symbol = "✘ "
format = "[ | $symbol$status]($style)"

[cmd_duration]
min_time = 2000
style = "bg:base02 fg:yellow"
format = "[ 󰞌 $duration]($style)"

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"
